name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to myapp directory
        run: cd myapp

      - name: Install dependencies
        run: npm install

      - name: Start the Server
        run: npm start

      
